import { Track, ComparisonPair, Beat } from './types';

export const DOOMGANG_DISCOGRAPHY: Track[] = [
  {
    id: 'doom-1',
    title: 'THE VOID CHRONICLES',
    artist: 'FPwonderful',
    year: '2024',
    category: 'album',
    accentColor: '#ACE1AF',
    bandcampUrl: 'https://fpwonderful.bandcamp.com',
    duration: '38:14',
    notes: 'A journey through liminal pressure, sub-harmonic weight, and clarity in the dark.',
  },
  {
    id: 'doom-2',
    title: 'ANALOG SANCTUARY',
    artist: 'FPwonderful',
    year: '2023',
    category: 'album',
    accentColor: '#C9A84C',
    bandcampUrl: 'https://fpwonderful.bandcamp.com',
    duration: '42:06',
    notes: 'Explorations in tape saturation, raw transient control, and acoustic space.',
  },
  {
    id: 'doom-3',
    title: 'CELADON FREQUENCIES',
    artist: 'FPwonderful',
    year: '2023',
    category: 'ep',
    accentColor: '#ACE1AF',
    bandcampUrl: 'https://fpwonderful.bandcamp.com',
    duration: '18:45',
    notes: 'Five movement ambient & trap synthesis EP.',
  },
  {
    id: 'doom-4',
    title: 'MIDNIGHT IN CHICAGO',
    artist: 'FPwonderful',
    year: '2022',
    category: 'single',
    accentColor: '#5E9F8A',
    bandcampUrl: 'https://fpwonderful.bandcamp.com',
    duration: '03:42',
    notes: 'Sub-bass study under city neon.',
  },
  {
    id: 'doom-5',
    title: 'RESTLESS DRIFT',
    artist: 'FPwonderful',
    year: '2022',
    category: 'single',
    accentColor: '#FF7F50',
    bandcampUrl: 'https://fpwonderful.bandcamp.com',
    duration: '04:10',
    notes: 'Intimate vocal staging with spatial grain.',
  },
  {
    id: 'doom-6',
    title: 'DOOM PROTOCOL // 001',
    artist: 'FPwonderful x DOOMgang',
    year: '2021',
    category: 'collab',
    accentColor: '#808000',
    bandcampUrl: 'https://fpwonderful.bandcamp.com',
    duration: '29:50',
    notes: 'Collaborative cipher and sonic architecture.',
  },
];

export const PRODUCTIONS_ARCHIVE: Track[] = [
  {
    id: 'prod-1',
    title: 'COLD TRUTH',
    artist: 'Prod. by FPwonderful (ft. Guest Vocalist)',
    year: '2024',
    category: 'production',
    accentColor: '#ACE1AF',
    duration: '03:22',
    notes: 'Full production, arrangement, vocal engineering, and master.',
  },
  {
    id: 'prod-2',
    title: 'SUB-AERO',
    artist: 'Prod. by FPwonderful',
    year: '2023',
    category: 'production',
    accentColor: '#C9A84C',
    duration: '02:58',
    notes: 'Heavyweight low-end design with Frutiger-clean top sparkle.',
  },
  {
    id: 'prod-3',
    title: 'INNER COMPASS',
    artist: 'Prod. by FPwonderful (ft. Chicago Collective)',
    year: '2023',
    category: 'production',
    accentColor: '#FF7F50',
    duration: '04:05',
    notes: 'Organic live percussion mixed into digital drum architecture.',
  },
  {
    id: 'prod-4',
    title: 'ECHO CHAMBER 312',
    artist: 'Prod. by FPwonderful',
    year: '2022',
    category: 'production',
    accentColor: '#5E9F8A',
    duration: '03:15',
    notes: 'Down-tempo reflective beat with custom tape-chopped keys.',
  },
];

export const COMPARISON_GALLERY: ComparisonPair[] = [
  {
    id: 'comp-trap',
    title: 'Heavy 808 & Vocal Clarity (Trap Demo)',
    genre: 'Trap / Hip-Hop',
    description: 'Notice how the raw track is muddy in the 200-400Hz region. In the master, the 808 punches with surgical definition without masking the vocal air.',
    unmixedSrc: '/audio/trap-unmixed.mp3',
    masteredSrc: '/audio/trap-mastered.mp3',
  },
  {
    id: 'comp-vocal',
    title: 'Vocal Chain Translation & Dynamic Depth',
    genre: 'Soul / R&B Vocal',
    description: 'Raw vocal felt harsh and detached. The finished analog processing provides tube warmth, precise de-essing, and transparent dynamic glue.',
    unmixedSrc: '/audio/vocal-unmixed.mp3',
    masteredSrc: '/audio/vocal-mastered.mp3',
  },
  {
    id: 'comp-master',
    title: 'Full Master Chain (Dynamic Punch vs Loudness)',
    genre: 'Alternative / Cinematic',
    description: 'We protect the transients and emotional crests while achieving industry-standard translation and competitive LUFS without squashing life.',
    unmixedSrc: '/audio/master-unmixed.mp3',
    masteredSrc: '/audio/master-mastered.mp3',
  },
];

export const PREVIOUS_WORK_PLAYLIST: Track[] = [
  {
    id: 'work-1',
    title: 'Nightfall In Hyde Park',
    artist: 'Marcus V. (Mix & Master by FPwonderful)',
    year: '2024',
    category: 'mix-master',
    duration: '03:45',
    notes: 'Analog summing, hybrid vocal chain, stereo field expansion.',
  },
  {
    id: 'work-2',
    title: 'Ghost In The Machine',
    artist: 'Aura K. (Mix & Master by FPwonderful)',
    year: '2023',
    category: 'mix-master',
    duration: '04:12',
    notes: 'Precision low-end phase alignment and tape warmth.',
  },
  {
    id: 'work-3',
    title: 'Southside Horizons',
    artist: 'The Collective (Mastered by FPwonderful)',
    year: '2023',
    category: 'mix-master',
    duration: '03:30',
    notes: 'Stem mastering for wide commercial translation.',
  },
  {
    id: 'work-4',
    title: 'Parallel Reality',
    artist: 'Eliot Vance (Mix & Master by FPwonderful)',
    year: '2022',
    category: 'mix-master',
    duration: '03:58',
    notes: 'Harmonic saturation and surgical resonance suppression.',
  },
];

export const BEATS_CATALOG: Beat[] = [
  {
    id: 'beat-01',
    title: 'Midnight Static',
    bpm: 140,
    key: 'C Min',
    tags: ['Trap', 'Dark', '808 Heavy', 'Chicago'],
    audioSrc: '/audio/beats/midnight-static.mp3',
    leasePrice: 29.99,
    exclusivePrice: 249.99,
    accentColor: '#ACE1AF',
  },
  {
    id: 'beat-02',
    title: 'Celadon Dreams',
    bpm: 85,
    key: 'F Min',
    tags: ['Lo-Fi', 'Soul', 'Warm Tape', 'Introspective'],
    audioSrc: '/audio/beats/celadon-dreams.mp3',
    leasePrice: 24.99,
    exclusivePrice: 199.99,
    accentColor: '#ACE1AF',
  },
  {
    id: 'beat-03',
    title: 'Orbital Decay',
    bpm: 160,
    key: 'D Min',
    tags: ['Cyber', 'Drill', 'Cinematic', 'Aggressive'],
    audioSrc: '/audio/beats/orbital-decay.mp3',
    leasePrice: 34.99,
    exclusivePrice: 299.99,
    accentColor: '#FF7F50',
  },
  {
    id: 'beat-04',
    title: 'Olive Sanctuary',
    bpm: 92,
    key: 'A Min',
    tags: ['Boom-Bap', 'Grounded', 'Soul Sample', 'Raw'],
    audioSrc: '/audio/beats/olive-sanctuary.mp3',
    leasePrice: 29.99,
    exclusivePrice: 249.99,
    accentColor: '#808000',
  },
  {
    id: 'beat-05',
    title: 'Liminal Space 312',
    bpm: 78,
    key: 'G# Min',
    tags: ['Ambient', '4D Sound', 'Ethereal', 'Spacious'],
    audioSrc: '/audio/beats/liminal-space.mp3',
    leasePrice: 24.99,
    exclusivePrice: 199.99,
    accentColor: '#ACE1AF',
  },
  {
    id: 'beat-06',
    title: 'Frequency Alignment',
    bpm: 130,
    key: 'B Min',
    tags: ['Melodic', 'Trap', 'Clean Transients', 'Vocal Chops'],
    audioSrc: '/audio/beats/frequency-alignment.mp3',
    leasePrice: 34.99,
    exclusivePrice: 299.99,
    accentColor: '#C9A84C',
  },
  {
    id: 'beat-07',
    title: 'Grid World',
    bpm: 96,
    key: 'E Min',
    tags: ['Cyberpunk', 'Heavy Drum', 'Analog Synths'],
    audioSrc: '/audio/beats/grid-world.mp3',
    leasePrice: 29.99,
    exclusivePrice: 249.99,
    accentColor: '#ACE1AF',
  },
  {
    id: 'beat-08',
    title: 'Signal & Noise',
    bpm: 144,
    key: 'D Min',
    tags: ['Hard', 'Dark', 'Distorted Sub', 'Energy'],
    audioSrc: '/audio/beats/signal-and-noise.mp3',
    leasePrice: 39.99,
    exclusivePrice: 349.99,
    accentColor: '#FF7F50',
  },
];
